"""Network/API extraction and interception routes.

HTTP handlers for the Network tab now live entirely in this router,
while reusing shared helpers and services from the core modules.
"""

import json
import time
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse

from logging_config import setup_logging

try:  # Support both package and script execution contexts for models
	from backend.app import models  # type: ignore
except ModuleNotFoundError:  # pragma: no cover - script mode (python backend/main.py)
	from app import models  # type: ignore

try:  # Service types and DI helpers
	from backend.app.services import (  # type: ignore
		APIExtractionService,
		get_api_extraction_service,
		get_screenshot_service,
	)
except ModuleNotFoundError:  # pragma: no cover - script mode
	from app.services import (  # type: ignore
		APIExtractionService,
		get_api_extraction_service,
		get_screenshot_service,
	)

try:
	from backend.main import _api_service_or_fallback  # type: ignore
except ModuleNotFoundError:  # pragma: no cover - script mode
	import main as _main  # type: ignore

	_api_service_or_fallback = _main._api_service_or_fallback  # type: ignore[attr-defined]


router = APIRouter()
logger = setup_logging(__name__)


@router.post("/api/network/export-curl")
async def export_network_events_as_curl(request: models.ExportCurlRequest):
	"""Export captured network events as cURL commands."""

	try:
		network_events = request.network_events or []

		if not network_events:
			return {"success": False, "error": "No network events provided"}

		# Convert to cURL commands using the shared screenshot service helper
		screenshot_service = get_screenshot_service()
		curl_commands = screenshot_service._convert_network_events_to_curl(network_events)

		if not curl_commands:
			return {"success": False, "error": "No API calls found in network events"}

		# Save to file
		curl_file = Path("screenshots/curl_commands.sh")
		curl_file.parent.mkdir(exist_ok=True)

		with open(curl_file, "w") as f:
			f.write("#!/bin/bash\n")
			f.write("# cURL commands exported from network events\n")
			f.write("# Generated by Screenshot Tool\n\n")
			for i, curl in enumerate(curl_commands, 1):
				f.write(f"# Request {i}\n")
				f.write(f"{curl}\n\n")

		return {
			"success": True,
			"curl_commands": curl_commands,
			"count": len(curl_commands),
			"file": str(curl_file),
		}
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Export cURL error: {str(e)}")
		return {"success": False, "error": str(e)}


@router.post("/api/network/extract")
async def extract_api_data(request: models.APIExtractionRequest):
	"""Placeholder for future API extraction from network logs.

	Currently this endpoint exists for forwards-compatibility and
	returns a simple success payload.
	"""

	try:
		logger.info(
			f"🌐 API extraction request: {request.url} -> {request.api_url_pattern}"
		)
		return JSONResponse(
			{
				"status": "success",
				"message": "API extraction feature coming soon",
				"request": {
					"url": request.url,
					"api_pattern": request.api_url_pattern,
				},
			}
		)
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ API extraction failed: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))


@router.post("/api/network/generate-metadata")
async def generate_metadata(
	request: models.GenerateMetadataRequest,
	api_service: APIExtractionService = Depends(get_api_extraction_service),
):
	"""Auto-generate metadata from an API response."""

	data = request.data
	prefix = request.prefix
	max_depth = request.max_depth

	logger.info(
		f"🌐 Generating metadata for API response (prefix: {prefix})"
	)

	return await _api_service_or_fallback(
		endpoint="generate-metadata",
		payload={"data": data, "prefix": prefix, "max_depth": max_depth},
		operation="Metadata generation",
		local_call=lambda: api_service.auto_generate_metadata(
			data,
			prefix=prefix,
			max_depth=max_depth,
		),
		response_builder=lambda metadata: {
			"status": "success",
			"metadata": metadata,
			"field_count": len(metadata),
		},
	)


@router.post("/api/network/extract-fields")
async def extract_fields(
	request_data: models.ExtractFieldsRequest,
	api_service: APIExtractionService = Depends(get_api_extraction_service),
):
	"""Extract fields from an API response using metadata mappings."""

	response_data = request_data.response_data
	field_mappings = request_data.field_mappings

	logger.info(
		f"🌐 Extracting {len(field_mappings)} fields from API response"
	)

	return await _api_service_or_fallback(
		endpoint="extract-fields",
		payload={
			"response_data": response_data,
			"field_mappings": field_mappings,
		},
		operation="Field extraction",
		local_call=lambda: api_service.extract_fields_from_response(
			response_data,
			field_mappings,
		),
		response_builder=lambda extracted: {
			"status": "success",
			"extracted_fields": extracted,
			"field_count": len(extracted),
		},
	)


@router.post("/api/network/validate")
async def validate_response(
	request_data: models.ValidateResponseRequest,
	api_service: APIExtractionService = Depends(get_api_extraction_service),
):
	"""Validate an API response against a metadata schema."""

	response_data = request_data.response_data
	metadata = request_data.metadata

	logger.info(
		f"🌐 Validating API response against {len(metadata)} fields"
	)

	return await _api_service_or_fallback(
		endpoint="validate",
		payload={"response_data": response_data, "metadata": metadata},
		operation="Validation",
		local_call=lambda: api_service.validate_response(
			response_data,
			metadata,
		),
		response_builder=lambda validation: {
			"status": "success",
			"validation": validation,
		},
	)


@router.post("/api/network/compare-environments")
async def compare_environments(
	request_data: models.CompareEnvironmentsRequest,
	api_service: APIExtractionService = Depends(get_api_extraction_service),
):
	"""Compare API responses across multiple environments."""

	extractions = request_data.extractions

	logger.info(
		f"🌐 Comparing API responses across {len(extractions)} environments"
	)

	return await _api_service_or_fallback(
		endpoint="compare-environments",
		payload={"extractions": extractions},
		operation="Environment comparison",
		local_call=lambda: api_service.compare_environments(extractions),
		response_builder=lambda comparison: {
			"status": "success",
			"comparison": comparison,
		},
	)


@router.get("/api/network/intercepted-apis")
async def get_intercepted_apis():
	"""Get all intercepted API responses."""

	try:
		screenshot_service = get_screenshot_service()
		apis = screenshot_service.intercepted_apis

		return JSONResponse(
			{
				"success": True,
				"count": len(apis),
				"apis": apis,
			}
		)
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Failed to get intercepted APIs: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))


@router.delete("/api/network/intercepted-apis")
async def clear_intercepted_apis():
	"""Clear all intercepted API responses."""

	try:
		screenshot_service = get_screenshot_service()
		count = len(screenshot_service.intercepted_apis)
		screenshot_service.intercepted_apis = []

		return JSONResponse(
			{
				"success": True,
				"message": f"Cleared {count} intercepted APIs",
			}
		)
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Failed to clear intercepted APIs: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))


@router.delete("/api/network/intercepted-apis/{api_id}")
async def delete_intercepted_api(api_id: str):
	"""Delete a specific intercepted API by ID."""

	try:
		screenshot_service = get_screenshot_service()
		original_count = len(screenshot_service.intercepted_apis)
		screenshot_service.intercepted_apis = [
			api
			for api in screenshot_service.intercepted_apis
			if api.get("id") != api_id
		]
		new_count = len(screenshot_service.intercepted_apis)

		if original_count == new_count:
			raise HTTPException(
				status_code=404, detail=f"API with ID {api_id} not found"
			)

		return JSONResponse(
			{
				"success": True,
				"message": f"Deleted API {api_id}",
				"remaining": new_count,
			}
		)
	except HTTPException:
		# Preserve explicit HTTP errors (e.g., 404 when API not found)
		raise
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Failed to delete intercepted API: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))


@router.post("/api/network/refresh-apis")
async def refresh_apis(request_data: models.RefreshApisRequest):
	"""Refresh API interception by reloading a URL.

	For now this returns a static message explaining that the feature
	requires loading the URL in Real Browser mode.
	"""

	try:
		url = request_data.url
		return JSONResponse(
			{
				"success": True,
				"message": "API refresh requires loading the URL in Real Browser mode",
				"url": url,
			}
		)
	except HTTPException:
		# Preserve explicit HTTP errors (e.g., 400 when URL is missing)
		raise
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Failed to refresh APIs: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))


@router.post("/api/network/add-manual-api")
async def add_manual_api(request_data: models.ManualApiRequest):
	"""Manually add an API response to the intercepted list."""

	try:
		url = request_data.url
		method = request_data.method
		status = request_data.status
		response_json = request_data.response_json

		api_entry = {
			"id": f"manual_{int(time.time() * 1000)}",
			"method": method,
			"url": url,
			"status": status,
			"statusText": "OK",
			"timestamp": 0,
			"request_headers": {},
			"response_headers": {},
			"request_body": None,
			"response_body": json.dumps(response_json),
			"response_json": response_json,
			"captured_at": time.time(),
			"page_url": "manual",
			"captured_from": "manual_entry",
		}

		screenshot_service = get_screenshot_service()
		screenshot_service.intercepted_apis.append(api_entry)

		if len(screenshot_service.intercepted_apis) > screenshot_service.max_intercepted_apis:
			screenshot_service.intercepted_apis = screenshot_service.intercepted_apis[
				-screenshot_service.max_intercepted_apis :
			]

		return JSONResponse(
			{
				"success": True,
				"message": "API added successfully",
				"api": api_entry,
			}
		)
	except Exception as e:  # pragma: no cover - defensive
		logger.error(f"❌ Failed to add manual API: {str(e)}")
		raise HTTPException(status_code=500, detail=str(e))
